Világos és sötét mód megváltoztatása
BME-MIT-IET/iet-hf-2022-funky_csumpa_kor pull request #5
Opened 2022-05-10 19:20 UTC by Popomester

Sötét módban alig olvasható szöveg láthatóvá tétele

2022-05-13 19:23 UTC, MrtnBalazs requested changes
Offset számolást szervezzük ki.

2022-05-13 19:23 UTC, MrtnBalazs commented on app/src/main/java/com/remenyo/papertrader/ui/components/Chart.kt
> +    val offset = -(calendar.get(ZONE_OFFSET) + calendar.get(DST_OFFSET)) / 1000
Az időzóna offset fölöslegesen van kiszámolva minden egyes alkalommal, meg kellene fontolni a kiszervezését, hogy csak első alkalommal kelljen kiszámolni.

2022-05-13 19:49 UTC, Popomester commented on app/src/main/java/com/remenyo/papertrader/ui/components/Chart.kt
> +    val offset = -(calendar.get(ZONE_OFFSET) + calendar.get(DST_OFFSET)) / 1000
Kiszervezem a számítást egy statikus attribútumba.

2022-05-14 12:51 UTC, MrtnBalazs approved these changes
Így rendben van.

2022-05-14 15:26 UTC, MrtnBalazs approved these changes
Rendben van.

2022-05-15 10:33 UTC, merged